### PR TITLE
feat: use luhn algorithm to generate account number

### LINKED ISSUE #48: Improve readability of account numbers
The account number algorithm generates incredibly hard to read/dictate alphanumeric results. Let's replace it with an algorithm that generates results of numbers only, ideally between 12-15 digits in length.

It would be good to add a checksum algorithm such as the [Luhn algorithm](https://en.wikipedia.org/wiki/Luhn_algorithm) so users get immediate feedback if they type (or paste) an incorrect (or incomplete) account number.

This is a usability improvement. **3746 4609 0019 3732** is a lot nicer than **1YaZwmxPpT7BxHI5fNVhVzUJo24**. 😱

### PR DESCRIPTION
**Pull request by maxyzli**
resolves #48

### CODE REVIEW

**Comment by geoffturk** [comment]
@LIYINGZHEN Looks good. Where in the code base does it check to ensure the account number is unique? We can't issue the same account number twice, even though the probability of that happening is small.

**Comment by maxyzli** [comment]
I have updated the code which checks uniqueness. Also, the DB schema makes sure the field is unique.

```
AccountNumber string  `gorm:"type:varchar(27);not null;unique_index"`
```

**Comment by geoffturk** [comment]
OK. What will happen when the generated number equals an existing one? It should try again until successful. Trying to avoid creating an entity but not giving it an account number.

**Review by geoffturk — APPROVED** [review]
LGTM 🚀

**Pull request merged**
