### PR TITLE
fix: No dateCompleted in cancelled/rejected/initiated transfers

### LINKED ISSUE #77: No dateCompleted in cancelled/rejected/initiated transfers
I missed this in my testing but we should not include the `dateCompleted` in cancelled transfers.

image

### PR DESCRIPTION
**Pull request by maxyzli**
resolves #77

### CODE REVIEW

**Comment by geoffturk** [comment]
Please fix this for initiated and cancelled transfers in `GET /transfers` as well:

image

**Review by geoffturk — APPROVED** [review]
(approved by mistake)

**Review by geoffturk — CHANGES_REQUESTED** [review]
See comment above.

**Comment by LIYINGZHEN** [comment]
@geoffturk It's hard to fix for `GET /transfers`.

**Review by geoffturk — APPROVED** [review]
LGTM 🚀

**Pull request merged**
