### PR TITLE
feat: create/update/delete category

### LINKED ISSUE #88: POST/PATCH/DELETE /admin/categories
Split this into separate issues/PRs if you want to work on them individually.

### PR DESCRIPTION
**Pull request by maxyzli**
Resolves #88

### CODE REVIEW

**Comment by geoffturk** [comment]
@LIYINGZHEN I found an interesting bug. Run the tests (everything under **Manage Categories and Tags**) I created for this PR. Then run them again. You will see 4 failed tests.

This is because when a tag is deleted and then recreated again, the same Mongo ID is being reused for it.

After the first run, here is the `categories` collection:
image

Now when I post to /admin/categories using the same category name, I get a 200 OK response (first two fails in the test suite).

Then a patch to /admin/categories/{categoryID} gives this 500 error:
```
{
    "errors": [
        {
            "message": "Category not found"
        }
    ]
}
```

What do you think is the best thing to do here?
1) delete the entire record (don't use the deletedAt parameter)
2) create a new record with a unique ID
3) "Undelete" (remove `deletedAt` & update `createdAt`) the category in the DB

I think option 3 is probably the best, as log as we log this activity so there is a record of what happened ("reinstated category: some-category-name").

**Review by geoffturk — CHANGES_REQUESTED** [review]
See above.

**Comment by maxyzli** [comment]
Screen Shot 2020-04-03 at 22 52 56

**Review by geoffturk — APPROVED** [review]
LGTM 🚀

**Pull request merged**
