### PR TITLE
feat: POST/PATCH/DELETE /admin/tags

### LINKED ISSUE #87: POST/PATCH/DELETE /admin/tags
Split this into separate issues/PRs if you want to work on them individually.

### PR DESCRIPTION
**Pull request by maxyzli**
resolves #87

### CODE REVIEW

**Comment by geoffturk** [comment]
These two tests are failing:

image

And creating these errors:

```
mccs        | [00] 2020-04-06T17:33:09.605Z	ERROR	middleware/recover.go:19	recover, error	{"err": "runtime error: index out of range [0] with length 0", "method": "goroutine 59 [running]:\ngithub.com/ic3network/mccs-alpha-api/internal/app/http/middleware.Recover.func1.1.1()\n\t/usr/src/app/internal/app/http/middleware/recover.go:18 +0xb8\npanic(0xf129c0, 0xc00023b3e0)\n\t/usr/local/go/src/runtime/panic.go:679 +0x1b2\ngithub.com/ic3network/mccs-alpha-api/util.InputToTag(0x0, 0x0, 0xc00034d8b0, 0x0)\n\t/usr/src/app/util/tag.go:28 +0x16e\ngithub.com/ic3network/mccs-alpha-api/internal/app/types.NewAdminCreateTagReqBody(0xc000220f00, 0x20, 0xc000331560, 0xc0003aee00, 0x7f826e5ee460)\n\t/usr/src/app/internal/app/types/api_request_body.go:530 +0x17d\ngithub.com/ic3network/mccs-alpha-api/internal/app/http/controller.(*adminTagHandler).create.func1(0x119c200, 0xc0002c40e0, 0xc000220f00)\n\t/usr/src/app/internal/app/http/controller/admin_tag_handler.go:45 +0x43\nnet/http.HandlerFunc.ServeHTTP(0xfdefe8, 0x119c200, 0xc0002c40e0, 0xc000220f00)\n\t/usr/local/go/src/net/http/server.go:2007 +0x44\ngithub.com/ic3network/mccs-alpha-api/internal/app/http/middleware.RequireAdmin.func1.1(0x119c200, 0xc0002c40"}
mccs        | [00] github.com/ic3network/mccs-alpha-api/internal/app/http/middleware.Recover.func1.1.1
mccs        | [00] 	/usr/src/app/internal/app/http/middleware/recover.go:19
mccs        | [00] runtime.gopanic
mccs        | [00] 	/usr/local/go/src/runtime/panic.go:679
mccs        | [00] runtime.goPanicIndex
mccs        | [00] 	/usr/local/go/src/runtime/panic.go:75
mccs        | [00] github.com/ic3network/mccs-alpha-api/util.InputToTag
mccs        | [00] 	/usr/src/app/util/tag.go:28
mccs        | [00] github.com/ic3network/mccs-alpha-api/internal/app/types.NewAdminCreateTagReqBody
mccs        | [00] 	/usr/src/app/internal/app/types/api_request_body.go:530
mccs        | [00] github.com/ic3network/mccs-alpha-api/internal/app/http/controller.(*adminTagHandler).create.func1
mccs        | [00] 	/usr/src/app/internal/app/http/controller/admin_tag_handler.go:45
mccs        | [00] net/http.HandlerFunc.ServeHTTP
mccs        | [00] 	/usr/local/go/src/net/http/server.go:2007
mccs        | [00] github.com/ic3network/mccs-alpha-api/internal/app/http/middleware.RequireAdmin.func1.1
mccs        | [00] 	/usr/src/app/internal/app/http/middleware/auth.go:70
mccs        | [00] net/http.HandlerFunc.ServeHTTP
mccs        | [00] 	/usr/local/go/src/net/http/server.go:2007
mccs        | [00] github.com/ic3network/mccs-alpha-api/internal/app/http/middleware.GetLoggedInUser.func1.1
mccs        | [00] 	/usr/src/app/internal/app/http/middleware/auth.go:34
mccs        | [00] net/http.HandlerFunc.ServeHTTP
mccs        | [00] 	/usr/local/go/src/net/http/server.go:2007
mccs        | [00] github.com/ic3network/mccs-alpha-api/internal/app/http/middleware.Logging.func1.1
mccs        | [00] 	/usr/src/app/internal/app/http/middleware/logging.go:37
mccs        | [00] net/http.HandlerFunc.ServeHTTP
mccs        | [00] 	/usr/local/go/src/net/http/server.go:2007
mccs        | [00] github.com/ic3network/mccs-alpha-api/internal/app/http/middleware.NoCache.func1.1
mccs        | [00] 	/usr/src/app/internal/app/http/middleware/cache.go:15
mccs        | [00] net/http.HandlerFunc.ServeHTTP
mccs        | [00] 	/usr/local/go/src/net/http/server.go:2007
mccs        | [00] github.com/ic3network/mccs-alpha-api/internal/app/http/middleware.Recover.func1.1
mccs        | [00] 	/usr/src/app/internal/app/http/middleware/recover.go:22
mccs        | [00] net/http.HandlerFunc.ServeHTTP
mccs        | [00] 	/usr/local/go/src/net/http/server.go:2007
mccs        | [00] github.com/gorilla/mux.(*Router).ServeHTTP
mccs        | [00] 	/go/pkg/mod/github.com/gorilla/mux@v1.7.3/mux.go:212
mccs        | [00] net/http.serverHandler.ServeHTTP
mccs        | [00] 	/usr/local/go/src/net/http/server.go:2802
mccs        | [00] net/http.(*conn).serve
mccs        | [00] 	/usr/local/go/src/net/http/server.go:1890
mccs        | [00] 2020-04-06T17:33:13.027Z	INFO	middleware/logging.go:29	request	{"ip": "172.20.0.1", "method": "POST", "uri": "/api/v1/admin/tags", "userAgent": "PostmanRuntime/7.24.0", "responseTime": "291.834µs"}
mccs        | [00] 2020-04-06T17:33:13.027Z	ERROR	middleware/recover.go:19	recover, error	{"err": "runtime error: index out of range [0] with length 0", "method": "goroutine 59 [running]:\ngithub.com/ic3network/mccs-alpha-api/internal/app/http/middleware.Recover.func1.1.1()\n\t/usr/src/app/internal/app/http/middleware/recover.go:18 +0xb8\npanic(0xf129c0, 0xc000466d20)\n\t/usr/local/go/src/runtime/panic.go:679 +0x1b2\ngithub.com/ic3network/mccs-alpha-api/util.InputToTag(0x0, 0x0, 0xc0001b7b60, 0x0)\n\t/usr/src/app/util/tag.go:28 +0x16e\ngithub.com/ic3network/mccs-alpha-api/internal/app/types.NewAdminCreateTagReqBody(0xc00053a300, 0x20, 0xc000426480, 0xc0003aea80, 0x7f826e5edd98)\n\t/usr/src/app/internal/app/types/api_request_body.go:530 +0x17d\ngithub.com/ic3network/mccs-alpha-api/internal/app/http/controller.(*adminTagHandler).create.func1(0x119c200, 0xc0002e6460, 0xc00053a300)\n\t/usr/src/app/internal/app/http/controller/admin_tag_handler.go:45 +0x43\nnet/http.HandlerFunc.ServeHTTP(0xfdefe8, 0x119c200, 0xc0002e6460, 0xc00053a300)\n\t/usr/local/go/src/net/http/server.go:2007 +0x44\ngithub.com/ic3network/mccs-alpha-api/internal/app/http/middleware.RequireAdmin.func1.1(0x119c200, 0xc0002e64"}
mccs        | [00] github.com/ic3network/mccs-alpha-api/internal/app/http/middleware.Recover.func1.1.1
mccs        | [00] 	/usr/src/app/internal/app/http/middleware/recover.go:19
mccs        | [00] runtime.gopanic
mccs        | [00] 	/usr/local/go/src/runtime/panic.go:679
mccs        | [00] runtime.goPanicIndex
mccs        | [00] 	/usr/local/go/src/runtime/panic.go:75
mccs        | [00] github.com/ic3network/mccs-alpha-api/util.InputToTag
mccs        | [00] 	/usr/src/app/util/tag.go:28
mccs        | [00] github.com/ic3network/mccs-alpha-api/internal/app/types.NewAdminCreateTagReqBody
mccs        | [00] 	/usr/src/app/internal/app/types/api_request_body.go:530
mccs        | [00] github.com/ic3network/mccs-alpha-api/internal/app/http/controller.(*adminTagHandler).create.func1
mccs        | [00] 	/usr/src/app/internal/app/http/controller/admin_tag_handler.go:45
mccs        | [00] net/http.HandlerFunc.ServeHTTP
mccs        | [00] 	/usr/local/go/src/net/http/server.go:2007
mccs        | [00] github.com/ic3network/mccs-alpha-api/internal/app/http/middleware.RequireAdmin.func1.1
mccs        | [00] 	/usr/src/app/internal/app/http/middleware/auth.go:70
mccs        | [00] net/http.HandlerFunc.ServeHTTP
mccs        | [00] 	/usr/local/go/src/net/http/server.go:2007
mccs        | [00] github.com/ic3network/mccs-alpha-api/internal/app/http/middleware.GetLoggedInUser.func1.1
mccs        | [00] 	/usr/src/app/internal/app/http/middleware/auth.go:34
mccs        | [00] net/http.HandlerFunc.ServeHTTP
mccs        | [00] 	/usr/local/go/src/net/http/server.go:2007
mccs        | [00] github.com/ic3network/mccs-alpha-api/internal/app/http/middleware.Logging.func1.1
mccs        | [00] 	/usr/src/app/internal/app/http/middleware/logging.go:37
mccs        | [00] net/http.HandlerFunc.ServeHTTP
mccs        | [00] 	/usr/local/go/src/net/http/server.go:2007
mccs        | [00] github.com/ic3network/mccs-alpha-api/internal/app/http/middleware.NoCache.func1.1
mccs        | [00] 	/usr/src/app/internal/app/http/middleware/cache.go:15
mccs        | [00] net/http.HandlerFunc.ServeHTTP
mccs        | [00] 	/usr/local/go/src/net/http/server.go:2007
mccs        | [00] github.com/ic3network/mccs-alpha-api/internal/app/http/middleware.Recover.func1.1
mccs        | [00] 	/usr/src/app/internal/app/http/middleware/recover.go:22
mccs        | [00] net/http.HandlerFunc.ServeHTTP
mccs        | [00] 	/usr/local/go/src/net/http/server.go:2007
mccs        | [00] github.com/gorilla/mux.(*Router).ServeHTTP
mccs        | [00] 	/go/pkg/mod/github.com/gorilla/mux@v1.7.3/mux.go:212
mccs        | [00] net/http.serverHandler.ServeHTTP
mccs        | [00] 	/usr/local/go/src/net/http/server.go:2802
mccs        | [00] net/http.(*conn).serve
mccs        | [00] 	/usr/local/go/src/net/http/server.go:1890
```

**Comment by geoffturk** [comment]
This test is returning the wrong error message:

image

image

**Comment by geoffturk** [comment]
Wrong error message here for these two as well:

image

image

**Review by geoffturk — CHANGES_REQUESTED** [review]
See above.

**Comment by maxyzli** [comment]
Screen Shot 2020-04-07 at 16 35 09

**Review by geoffturk — CHANGES_REQUESTED** [review]
Looking good. One more change please: let's use the Tag sanitization regexes for Categories as well. So a category should be "a-unique-category" instead of "A Unique Category".

I've updated the tests to reflect this so they should all pass when the change is made.

**Comment by maxyzli** [comment]
Screen Shot 2020-04-07 at 18 07 07

**Review by geoffturk — APPROVED** [review]
LGTM 🚀

**Pull request merged**
