### PR TITLE
feat: admin login/logout

### LINKED ISSUE #79: POST /admin/login

### LINKED ISSUE #80: POST /admin/logout

### PR DESCRIPTION
**Pull request by maxyzli**
resolves #79 
resolves #80

### CODE REVIEW

**Review by geoffturk — CHANGES_REQUESTED** [review]
We need to enforce the 15 minute account lockout after 3 failed login attempts, just like we do for users.

image

I've set up tests in **MCCS Alpha Admin API - v0.1 - Tests**.

**Comment by maxyzli** [comment]
Screen Shot 2020-04-01 at 15 18 00

**Review by geoffturk — CHANGES_REQUESTED** [review]
The `loginAttempts` counter needs to be reset each time after a successful login, otherwise you get locked out after 3 failed logins even if they are not consecutive.

image

**Comment by geoffturk** [comment]
@LIYINGZHEN Please fix this for the user login as well if it is not the case already.

**Comment by maxyzli** [comment]
Screen Shot 2020-04-01 at 18 38 40

**Review by geoffturk — APPROVED** [review]
LGTM 🚀

**Pull request merged**
