### PR TITLE
feat: cors

### PR DESCRIPTION
**Pull request by maxyzli**

### CODE REVIEW

**Review by geoffturk — CHANGES_REQUESTED** [review]
There's an issue with authentication being required now for endpoints that didn't need it before:

```
(cors ✔) ᐅ curl http://localhost:8080/api/v1/categories
{"errors":[{"message":"Could not authenticate you."}]}%
(cors ✔) ᐅ gco dev
Switched to branch 'dev'
Your branch is up to date with 'origin/dev'.
(dev ✔) ᐅ curl http://localhost:8080/api/v1/categories
{"data":["Carpentry","Painting","Car Repair","Brewery","Restaurant","Transport","Organic Produce","Bakery"],"meta":{"numberOfResults":8,"totalPages":1}}%
```

**Review by geoffturk — CHANGES_REQUESTED** [review]
All the User API tests are breaking. Here's them on the `dev` branch (all passing):

image

And on the `cors` branch (breaking everywhere and not even finishing):

image

Just looking at the first tests in the screenshot above, we should not be getting 401 errors on the signup endpoint.

Please make sure the test suites are passing (except for the Admin API for entities which is still work in progress) before submitting for review.

**Comment by maxyzli** [comment]
@geoffturk Sorry, I don't know how to recreate your problems.

Screen Shot 2020-04-20 at 18 36 04

**Comment by geoffturk** [comment]
@LIYINGZHEN Sorry, that was my fault. I forgot to pull in your latest commit. 🤦

Tests are all passing and the GET requests are working fine now.

However, POST requests are still failing.

Firefox:

Screen Shot 2020-04-20 at 13 33 12

Chrome:

Screen Shot 2020-04-20 at 13 33 38

**Comment by geoffturk** [comment]
Seems the server needs to be able to handle preflighted requests (scroll down to the "Preflighted requests" section):
https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS#Examples_of_access_control_scenarios

**Comment by geoffturk** [comment]
@LIYINGZHEN Maybe something here is useful:
https://stackoverflow.com/questions/22972066/how-to-handle-preflight-cors-requests-on-a-go-server

**Comment by maxyzli** [comment]
@geoffturk I have used a package. We don't need to worry about that at all.

**Comment by geoffturk** [comment]
OK. The last commits did not fix it though. Still getting the same errors in both Chrome and Firefox.

**Comment by geoffturk** [comment]
@LIYINGZHEN See my comments in Telegram. The server is not returning CORS preflights requests correctly, which means there must be further configuration needed.

**Review by geoffturk — APPROVED** [review]
It's working now. 🚀 

image

**Pull request merged**
