### PR TITLE
feat: send welcome email

### LINKED ISSUE #136: Send welcome email when new account created after POST /signup
Send the welcome email to the entity's email address (which will be the user's email address unless `entityEmail` is specified during signup) after the user and entity have been created in the DB.

### PR DESCRIPTION
**Pull request by maxyzli**
resolves #136

**Remember to change `development.yaml`**

### CODE REVIEW

**Review by geoffturk — DISMISSED** [review]
LGTM 🚀

**Comment by geoffturk** [comment]
@LIYINGZHEN Even with the env var set to true, I am not receiving the signup notification emails (`SendSignupNotification` in `internal/pkg/email/email.go`).

image

Usually a signup notification email should be sent to the email in  the env var `sendgrid: sender_email`.

**Comment by maxyzli** [comment]
@geoffturk This is only for sending the welcome email. And you didn't create the issue so I think you don't need the email anymore.

**Comment by geoffturk** [comment]
@LIYINGZHEN OK, I created another for this.

**Pull request merged**
