### PR TITLE
feat: log user actions

### LINKED ISSUE #90: Log admin and user POST/PATCH/DELETE actions

### LINKED ISSUE #108: GET /admin/logs
Search Parameters:

- Date from/to
- Email
- Category (admin, user, all/both)
- Fragment search (i.e., partial match/fuzzy match) in:
  - Action
  - Details

Fragment search in Action and Detail columns give more granular search control for specific changes.

Make sure to enable pagination since number of results will be significant.

### PR DESCRIPTION
**Pull request by maxyzli**
resolves #90 
resolves #108

### CODE REVIEW

**Comment by geoffturk** [comment]
Please add the ability to view logs based on email:

image

**Review by geoffturk — CHANGES_REQUESTED** [review]
See above.

And as discussed, there is the issue with the pointer to a struct in the slice for the offers/wants tags.

Once these are done it is good to merge.

**Comment by maxyzli** [comment]
User tests

Screen Shot 2020-05-17 at 09 36 34

Admin tests

Screen Shot 2020-05-17 at 09 37 16

Log

Screen Shot 2020-05-17 at 09 37 54

**Comment by geoffturk** [comment]
image

These log tests are still failing. Also, you only are showing 626 admin tests when there are 648. Logout/in again to resync the tests.

**Review by geoffturk — APPROVED** [review]
LGTM 🚀

**Pull request merged**
