### PR TITLE
feat: get /user API

### LINKED ISSUE #5: Create ​/user APIs

### PR DESCRIPTION
**Pull request by maxyzli**
part of #5

### CODE REVIEW

**Comment by geoffturk** [comment]
Please map `userPhone` to `telephone` in the User record (and the Entity record too when you implement that).

Also, use return 201 Created instead of 200 OK in the response from `POST /signup`.

**Review by geoffturk — CHANGES_REQUESTED** [review]
See above.

**Comment by maxyzli** [comment]
@geoffturk  Why use 201 Created? We have discussed it before right? We don't return the location anymore. 

Check out https://github.com/ic3network/mccs-alpha-api/pull/3#issuecomment-578488774

**Comment by geoffturk** [comment]
https://stackoverflow.com/a/24305071/10310551

Let's keep the User resource link in the Location header and have the IDs to both resources in the body of the response.

**Comment by geoffturk** [comment]
As discussed, let's just go with 200 for now and leave out Location header.

**Review by geoffturk — APPROVED** [review]
We're good to go here... 🚀

**Pull request merged**
