### PR TITLE
Create an entity during user signup

### LINKED ISSUE #12: Create an entity during user signup

### PR DESCRIPTION
**Pull request by maxyzli**
resolves #12

### CODE REVIEW

**Comment by geoffturk** [comment]
OK. Let's return the entityID and the userID along with the token in the body of the response:

```
201 Created

{
  data: {
    "userID": "...",
    "entityID": "...",
    "token": "ey..."
  }
}
```

And remove the `Location` header with the User resource URL. API users may not make use of them but we should return them anyway in case they want to.

**Comment by geoffturk** [comment]
Also, accept all other relevant fields as input into the User and/or Entity resources that are being created.

**User**
```
firstName
lastName
userPhone (not telephone)
ShowRecentMatchedTags
DailyNotification
FavoriteEntities
```

**Entity**
```
entityName
incType
companyNumber
entityPhone
website
turnover
description
locationAddress
locationCity
locationRegion
locationPostalCode
locationCountry
```

**Review by geoffturk — CHANGES_REQUESTED** [review]
Looking good. See my additions above.

I'll start writing tests for them while you code it up.

**Comment by geoffturk** [comment]
See the **Signup User & Entity** folder that I have added to the test suite.

Also try out the tests  in the **User Management** folder as well.

**Comment by LIYINGZHEN** [comment]
> OK. Let's return the entityID and the userID along with the token in the body of the response:
> 
> ```
> 201 Created
> 
> {
>   data: {
>     "userID": "...",
>     "entityID": "...",
>     "token": "ey..."
>   }
> }
> ```
> 
> And remove the `Location` header with the User resource URL. API users may not make use of them but we should return them anyway in case they want to.

Then we should probably use 200 success.

**Comment by LIYINGZHEN** [comment]
I don't think this is a good design. It's hard to tell which fields belong to User or Entity. 

```
{
	"email": "{{testUserEmail}}",
	"password": "{{defaultPassword}}",
	"firstName": "Jane",
	"lastName": "Doe",
	"userPhone": "+442071234567",
	"ShowRecentMatchedTags": "true",
	"DailyNotification": "true",
	"FavoriteEntities": [""],
	"entityName": "Jane's Bakery",
	"incType": "sole",
	"companyNumber": "none",
	"entityPhone": "+442077654321",
	"website": "https://janebake.co.uk",
	"turnover": 10000,
	"description": "We bake cakes!",
	"locationAddress": "123 Main",
	"locationCity": "London",
	"locationRegion": "Greater London",
	"locationPostalCode": "LN1 UK2",
	"locationCountry": "England"
}
```

**Review by geoffturk — CHANGES_REQUESTED** [review]
The user first/last names and telephone need to also be written to the user record (so far only entity data being written to the entity record).

Also, the GET /user test is failing (404 not found). We need GET /entity as well (I will write a test for that).

**Review by geoffturk — APPROVED** [review]

**Pull request merged**
