### PR TITLE
feat: post /transfers

### LINKED ISSUE #67: Create POST /transfers

### PR DESCRIPTION
**Pull request by maxyzli**
resolves #67

### CODE REVIEW

**Comment by maxyzli** [comment]
- `initiator` is the one makes proposals.
- `receiver` is the one receives emails.

### Feel free to change the naming from the following definitions.

- [TransferReqBody](https://github.com/ic3network/mccs-alpha-api/pull/69/files#diff-50892201a4170aba773e98e4d713f893R355)
- [TransferProposal](https://github.com/ic3network/mccs-alpha-api/pull/69/files#diff-6bf8390863c26213f48d586b2e6c6b29R9)
- [Journal Schema](https://github.com/ic3network/mccs-alpha-api/pull/69/files#diff-7e32e12f2bd924439735d7ea8bda7f34R7)
- [ProposeTransferRespond](https://github.com/ic3network/mccs-alpha-api/pull/69/files#diff-2ea59b6917c879bee352d9b1019c829fR153)

## Tests

Screen Shot 2020-03-17 at 15 35 38

**Comment by geoffturk** [comment]
See the new tests in the test suite. This 500 error should really be a 400:
image

Also, please implement #70 in a separate PR. I need to preset the max negative balance limits for  the test accounts to finish adding tests for `POST /transfer` and will need it for `PATCH /transfers/{transferID}` as well.

**Review by geoffturk — CHANGES_REQUESTED** [review]
See comments above.

**Comment by geoffturk** [comment]
@LIYINGZHEN Alternatively, if it is easier, just update `PATCH /admin/entities/:entityID` so we can modify `max_neg_ bal` and `max_pos_bal` per entity and I can make the changes directly in the tests.

**Review by geoffturk — APPROVED** [review]
LGTM 🚀 

Over 600 tests now in the suite...

image

**Pull request merged**
