### PR TITLE
feat: PATCH /admin/entities/{entityID}

### LINKED ISSUE #33: [API] PATCH admin/entities/{entityID}
Start with updating entity `status`.

### LINKED ISSUE #54: Validate email length and correctness in PATCH /user/entities/{entityID}
The email length and correctness (e.g., has an @, a dot-TLD at the end,  etc.) needs to be validated when an email is updated for an  entity.

### PR DESCRIPTION
**Pull request by maxyzli**
resolves #33
resolves #54

### CODE REVIEW

**Comment by geoffturk** [comment]
@LIYINGZHEN As discussed, once the other two remaining issues (#31 & #45) are done and merged, merge the dev branch into this PR and I will review and setup the admin API test suite for it.

**Comment by maxyzli** [comment]
@geoffturk Done. I forced push due to some merge issues. Please delete the branch and pull it again.

**Review by geoffturk — CHANGES_REQUESTED** [review]
Looking good. A couple of changes:

- Return 401 error when trying unauthorized (not logged in) requests instead of 500 error
- Returning `isFavorite` in the response makes no sense for an admin - please remove it

**Review by geoffturk — CHANGES_REQUESTED** [review]
See #54.

**Comment by geoffturk** [comment]
Not working:
image

**Review by geoffturk — APPROVED** [review]
LGTM 🚀

**Pull request merged**
