### PR TITLE
fix: check QueryingEntityID

### LINKED ISSUE #61: Only show isFavorite: true to authenticated and authorized users of querying entity
When searching for an entity while specifying the `querying_entity_id`, it is possible for anyone to see if the searched entity is a favorite of another entity. This should be restricted so only a logged-in user who is associated to the `querying_entity_id` is able to see if `isFavorite` is  true or false. 

See the failing tests in the test suite:
image

### PR DESCRIPTION
**Pull request by maxyzli**
resolves #61

### CODE REVIEW

**Comment by maxyzli** [comment]
| Login | Provide QueryingEntityID | QueryingEntityID Owner | Result        |
|------------|------------------|------------------------|---------------|
| False      | True             | x                      | 401 Unauthorized |
| False      | false            | x                      | OK            |
| True       | True             | False                  | 403 Forbidden |
| True       | True             | True                   | OK            |
| True       | false            | x                      | OK            |

**Review by geoffturk — CHANGES_REQUESTED** [review]
Looks good for the first part of the issue. Please take a look at my second comment in the issue and the 4 tests that are still failing as a result.

**Comment by maxyzli** [comment]
Sorry. I didn't run the entire entity tests. Right now, all the tests pass.

Screen Shot 2020-03-15 at 23 04 00

**Review by geoffturk — APPROVED** [review]
LGTM 🚀

**Pull request merged**
