### PR TITLE
Create PATCH /transfers​/{transferID}

### LINKED ISSUE #68: Create PATCH /transfers​/{transferID}

### PR DESCRIPTION
**Pull request by maxyzli**
resolves #68

### CODE REVIEW

**Comment by geoffturk** [comment]
@LIYINGZHEN Take a look at the two error messages below. Where are they coming from? I don't see either of them anywhere in the code.

image

image

**Comment by maxyzli** [comment]
You didn't provide the correct `transferID` and another one is coming from the JSON package.

**Comment by geoffturk** [comment]
`record not found` is from Postgres?

**Comment by geoffturk** [comment]
I guess `record not found` is coming directly from PostgreSQL as well.

**Comment by maxyzli** [comment]
You didn't provide the correct `transferID` so PostgreSQL returns record not found.

**Comment by geoffturk** [comment]
OK, but with your last push it is now returning `Could not authenticate you.`, but that is not the issue. Can you get it to return a custom message about not finding the record, or if necessary, just return the PostgreSQL error directly?

**Comment by geoffturk** [comment]
The generic `Could not authenticate you` doesn't make sense in either of these cases. Instead it is an issue of either a non-existent body or an incorrect transfer ID. Either cater for these two individually, or just revert back to what we had if it is too complicated. We can circle back to it later when we deal with #10.

**Comment by geoffturk** [comment]
The generic `Could not authenticate you` doesn't make in either of the case of an incorrect transfer ID. Please provide the correct message for this one too, or just revert back to what we had if it is too complicated. We can circle back to it later when we deal with #10.

**Review by geoffturk — APPROVED** [review]
LGTM :rocket:

**Pull request merged**
